OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"
          - "0.0.0.0"

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org4
    Domain: org4.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org5
    Domain: org5.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org6
    Domain: org6.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org7
    Domain: org7.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1
  
  - Name: Org8
    Domain: org8.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org9
    Domain: org9.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org10
    Domain: org10.example.com
    Template:
      Count: 50
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1