version: '2'

networks:
  basic:

volumes:
  mychannel_init_block:

services:
  ca.example.com:
    container_name: ca.example.com
    image: hyperledger/fabric-ca:1.4.8
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.example.com
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
    - "6054:6054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
    - ./crypto-config/ordererOrganizations/example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
    - basic

  ca.org1.example.com:
    container_name: ca.org1.example.com
    image: hyperledger/fabric-ca:1.4.8
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
    - "1154:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
    - basic

  ca.org2.example.com:
    container_name: ca.org2.example.com
    image: hyperledger/fabric-ca:1.4.8
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
    - "1254:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
    - basic

  ca.org3.example.com:
    container_name: ca.org3.example.com
    image: hyperledger/fabric-ca:1.4.8
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.org3.example.com
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
    - "1354:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
    - basic

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: docker-compose-base.yml
      service: orderer-base
    environment:
    - CORE_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
    ports:
    - 7050:7050
    - 7052:9443
    volumes:
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/etc/hyperledger/orderer/tls
    networks:
    - basic

  couchdb.peer01.example.com:
    container_name: couchdb.peer01.example.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5901:5984
    networks:
      - basic

  couchdb.peer11.example.com:
    container_name: couchdb.peer11.example.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5911:5984
    networks:
      - basic

  couchdb.peer02.example.com:
    container_name: couchdb.peer02.example.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5902:5984
    networks:
      - basic

  couchdb.peer12.example.com:
    container_name: couchdb.peer12.example.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - basic

  couchdb.peer03.example.com:
    container_name: couchdb.peer03.example.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5903:5984
    networks:
      - basic

  couchdb.peer13.example.com:
    container_name: couchdb.peer13.example.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5913:5984
    networks:
      - basic

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer01.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_ID=peer0.org1.example.com
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:9443
    ports:
    - 1151:7051
    - 55798:9443
    volumes:
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/peer/tls
    - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/users
    - ./../core/:/core
    depends_on:
    - orderer.example.com
    - couchdb.peer01.example.com
    networks:
    - basic

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer01.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_ID=peer1.org1.example.com
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:9443
    ports:
    - 9930:7051
    - 55132:9443
    volumes:
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/peer/msp
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/peer/tls
    - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/users
    - ./../core/:/core
    depends_on:
    - orderer.example.com
    - couchdb.peer11.example.com
    networks:
    - basic

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer01.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_ID=peer0.org2.example.com
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.example.com:9443
    ports:
    - 1251:7051
    - 48294:9443
    volumes:
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/peer/msp
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/peer/tls
    - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/users
    - ./../core/:/core
    depends_on:
    - orderer.example.com
    - couchdb.peer02.example.com
    networks:
    - basic

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer01.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_ID=peer1.org2.example.com
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org2.example.com:9443
    ports:
    - 10870:7051
    - 54732:9443
    volumes:
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/peer/msp
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/peer/tls
    - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/users
    - ./../core/:/core
    depends_on:
    - orderer.example.com
    - couchdb.peer12.example.com
    networks:
    - basic

  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer01.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_ID=peer0.org3.example.com
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org3.example.com:9443
    ports:
    - 1351:7051
    - 50075:9443
    volumes:
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/peer/msp
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/peer/tls
    - ./crypto-config/peerOrganizations/org3.example.com/users:/etc/hyperledger/users
    - ./../core/:/core
    depends_on:
    - orderer.example.com
    - couchdb.peer03.example.com
    networks:
    - basic

  peer1.org3.example.com:
    container_name: peer1.org3.example.com
    extends:
      file: docker-compose-base.yml
      service: peer-base
    environment:
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer01.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_ID=peer1.org3.example.com
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_PEER_ADDRESS=peer1.org3.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:7051
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org3.example.com:9443
    ports:
    - 8537:7051
    - 50038:9443
    volumes:
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/peer/msp
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/peer/tls
    - ./crypto-config/peerOrganizations/org3.example.com/users:/etc/hyperledger/users
    - ./../core/:/core
    depends_on:
    - orderer.example.com
    - couchdb.peer13.example.com
    networks:
    - basic

  prometheus.example.com: 
    container_name: prometheus.example.com
    image: prom/prometheus 
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml       
    volumes: 
        - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    networks: 
        - basic
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com      
       - peer1.org1.example.com  
       - peer0.org2.example.com  
       - peer1.org2.example.com  
       - peer0.org3.example.com  
       - peer1.org3.example.com

  grafana.example.com:
    container_name: grafana.example.com
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - basic
    depends_on:
      - prometheus.example.com